### ISSUE TITLE
utils/sentence_feature_extractor.py and `sentence_feature_extractor.py` in evadb repo

### ISSUE THREAD

**Issue by xzdandy** [georgia-tech-db/evadb-slack-bot#2]
Evadb comes with [sentence_feature_extractor.py](https://github.com/georgia-tech-db/evadb/blob/staging/evadb/functions/sentence_feature_extractor.py). Is there a particular reason we need to copy the file instead of directly using the one comes with the evadb? If we can not `CREATE FUNCTION` using functions in evadb repo, that is an issue we need to fix. Thanks.

**Comment by jiashenC** [comment]
We can do that. We are just too lazy to copy from the EvaDB repo 🙂.

**Comment by xzdandy** [comment]
Created https://github.com/georgia-tech-db/evadb/issues/1105 for improving user experience when building apps that needs built-in functions that are not auto loaded.
